============================= test session starts =============================
platform win32 -- Python 3.13.2, pytest-8.3.5, pluggy-1.5.0 -- d:\OneDrive\Documents\SeanDev\AITypingTrainer\.venv\Scripts\python.exe
cachedir: .pytest_cache
PyQt5 5.15.11 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
rootdir: D:\OneDrive\Documents\SeanDev\AITypingTrainer
plugins: mock-3.14.0, qt-4.4.0
collecting ... collected 0 items / 1 error

=================================== ERRORS ====================================
_______________ ERROR collecting tests/api/test_snippet_api.py ________________
ImportError while importing test module 'D:\OneDrive\Documents\SeanDev\AITypingTrainer\tests\api\test_snippet_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Python\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\api\test_snippet_api.py:3: in <module>
    from api.snippet_api import snippet_api
api\snippet_api.py:3: in <module>
    from db.models.practice_generator import PracticeGenerator
E   ModuleNotFoundError: No module named 'db.models'
=========================== short test summary info ===========================
ERROR tests/api/test_snippet_api.py
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 0.49s ===============================
